ath10k-bdencoder: Fix ATH10K_BOARD_SIGNATURE handling
The script call to unpack a board-2.bin always failed:

  invalid signature found in board-2.bin
  Traceback (most recent call last):
    File "./tools/scripts/ath10k/ath10k-bdencoder", line 736, in <module>
      main()
    File "./tools/scripts/ath10k/ath10k-bdencoder", line 723, in main
      return cmd_extract(args)
    File "./tools/scripts/ath10k/ath10k-bdencoder", line 443, in cmd_extract
      for board in cont.boards:
  AttributeError: 'int' object has no attribute 'boards'

Fixes: c2bd6f580d16 ("Update ath10k-bdencoder to run properly with Python 3")
Signed-off-by: Sven Eckelmann <sven@narfation.org>